### ISSUE TITLE
[Bug]: v2.0.10 - VirusTotal reports 8 "identical" infections.

### ISSUE THREAD

**Issue by l1m3r** [Digitalroot-Valheim/Digitalroot.Valheim.SlopeCombatFix#3]
### How are you playing the game?

Multiplayer - Dedicated Server

### What happened?

I uploaded the [current release](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.SlopeCombatFix/releases/tag/v2.0.10) to VirusTotal and got [theses results](https://www.virustotal.com/gui/file/d1f41750698b6f68964f7bb885362e7c3ddb7809f119b06f31177c35662c5fd3?nocache=1).
```
Arcabit Trojan.Tedy.D5BFE0
BitDefender Gen:Variant.Tedy.376800
Emsisoft Gen:Variant.Tedy.376800 (B)
eScan Gen:Variant.Tedy.376800
GData Gen:Variant.Tedy.376800
MAX Malware (ai Score=86)
Trellix (FireEye) Gen:Variant.Tedy.376800
VIPRE Gen:Variant.Tedy.376800
```

### To Reproduce

(not relevant in this case)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by l1m3r** [comment]
heh, I'm not even using this specific mod. :-)
Just stumbled over [this thread](https://steamcommunity.com/app/892970/discussions/1/3841053719660621875/) and I thought I might warn you (to enable you) to prevent potential "bad publicity" (even false positives can cause that).

**Comment by Digitalroot** [comment]
Thank you very much. I'll post something

**Comment by Digitalroot** [comment]
I am the author of the mod. These are false positives. The code is public, you are welcome to review it and compile it yourself if you are concerned.

I just grabbed the same version Digitalroot.Valheim.SlopeCombatAssistance.v2.0.10.ts.zip (47aab7c094216c2e4dbf9f59e27af1f8) off github. The hash matches what is in the scan. 

I decompiled the dll and looked at what was inside, just to make sure something in the build pipeline wasn't compromised. I do not see anything in the code that I did not expect to find. 

I also grabbed the NexusMods version of the mod "Digitalroot.Valheim.SlopeCombatAssistance.v2.0.10.zip", and submitted it https://www.virustotal.com/gui/file/af2936f3c78f12aecfef9ede33e5ec56cd50de12a615e0ad545494bd58f23ea8 the DLL in both zip files are the same. File is clean. 

Here is the hash of the two dlls. 
ts.Digitalroot.Valheim.SlopeCombatAssi...      2dbd5109063c2329ea89ce587a1ff617
nx.Digitalroot.Valheim.SlopeCombatAssi...      2dbd5109063c2329ea89ce587a1ff617

Here is the scan of each file in the zip. 

Digitalroot.Valheim.SlopeCombatAssistance.dll (2dbd5109063c2329ea89ce587a1ff617)
https://www.virustotal.com/gui/file/8910f46ab7049637fde43d6d5adee8c8e467f827f0a80420011d29505ae6a882

LICENSE (4ae09d45eac4aa08d013b5f2e01c67f6)
https://www.virustotal.com/gui/file/8486a10c4393cee1c25392769ddd3b2d6c242d6ec7928e1414efff7dfb2f07ef

icon.png (3d7766392d03d5b79a243ba6dc7e2594)
https://www.virustotal.com/gui/file/d4a8371da448c8bdd2ae62b7ece27defff11c3ebabacaf899a3d0a9c9ba35592

manifest.json (410ee4ad89bba8938105986ef3e98f15)
https://www.virustotal.com/gui/file/30afbe8ddaf2763226c68368c3f92e10ffaf68cee2134b40869b15f5a4a7641e

README.md (518f1b3cdca9f2f5fc9391f560322201)
https://www.virustotal.com/gui/file/979c4d3cf50a8569e06008e739720d9c2d6cf292023fd924e25461dfe9703f17

Each file tests clean.
