### ISSUE TITLE
[Bug]: Zip gets quarantined after download

### ISSUE THREAD

**Issue by icemansparks** [Digitalroot-Valheim/Digitalroot.Valheim.SlopeCombatFix#4]
### How are you playing the game?

Single Player - No Server

### What happened?

Windows identifies a security issue with the latest zip file. The file is automatically put into quarantine.

### To Reproduce

1. Go to 'Versions in this repo' 
2. Click on 'download zip'
3. See windows defender pop up and put file to quarantine

### Screenshots

![quarantined](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.SlopeCombatFix/assets/11578975/a8f9910b-720f-4dc3-8365-6d9cf35b2387)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by icemansparks** [comment]
> Do you have the same problem with the file downloaded from TS? https://valheim.thunderstore.io/package/Digitalroot/Digitalroots_Slope_Combat_Assistance/

No, The download from there seems to be ok. But the File is outdated (2.0.9) so i went to download from the repo instead.

**Comment by Digitalroot** [comment]
Updating the file on TS.

**Comment by icemansparks** [comment]
No problems when loading over TS now, thanks :)
